// <auto-generated />
namespace ContosoUniversity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixMigrationErrors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixMigrationErrors));
        
        string IMigrationMetadata.Id
        {
            get { return "201406171243318_FixMigrationErrors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
