using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversity.Models
{
    public class Course
    {
        // primary key; have it not automatically generated by database.
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int ID { get; set; }

        public string Title { get; set; }
        public int Credits { get; set; }

        // navigation property
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}