using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversity.Models
{
    public class Course
    {
        // primary key; have it not automatically generated by database.
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Course Number")]
        public int ID { get; set; }

        [StringLength(10, MinimumLength = 3)]
        public string Title { get; set; }

        [Range (0, 5)]
        public int Credits { get; set; }

        public int DepartmentID { get; set; }


        // navigation properties
        public virtual Department Department { get; set; }
        public virtual ICollection<Instructor> Instructors { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}